version: '3.2'

services:

  deter-sar:
    image: terrabrasilis/deter-sar-ftp-download:v0.1.0
    volumes:
      - /data/deter-sar/download-sar-ftp:/usr/local/data
    secrets:
      - postgres.user.forest.monitor
      - postgres.pass.forest.monitor
      - ftp.dpi.user
      - ftp.dpi.pass
    environment:
      FTP_USER: /run/secrets/ftp.dpi.user
      FTP_PASS: /run/secrets/ftp.dpi.pass
      POSTGRES_USER_FILE: /run/secrets/postgres.user.forest.monitor
      POSTGRES_PASS_FILE: /run/secrets/postgres.pass.forest.monitor
    networks:
      - proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.nodename==node3.master.cluster2
      restart_policy:
        condition: on-failure

secrets:
  postgres.user.forest.monitor:
    external: true
  postgres.pass.forest.monitor:
    external: true
  ftp.dpi.user:
    external: true
  ftp.dpi.pass:
    external: true

networks:
  proxy:
    external: true