version: '3.2'

services:

  # this file is a fragment used in "deterb_data_sync" on portainer.
# http://terrabrasilis.dpi.inpe.br/portainer/#/stacks/deterb_data_sync?id=19&type=1&external=false
  ftp-download:
    image: terrabrasilis/deter-ftp-download:v0.1
    volumes:
      - /data/deterb-sync/download-ftp:/usr/local/data
    secrets:
      - postgres.user.deter.amz
      - postgres.pass.deter.amz
    networks:
      - proxy
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.labels.master1==master1
      restart_policy:
        condition: on-failure
# ------------------------------------------------------------

networks:
  proxy:
    external: true