# To run this compose file
# docker-compose -f raster-publisher-env/docker-compose.yml up
#
# To run in detached mode
# docker-compose -f raster-publisher-env/docker-compose.yml up -d

version: "3.2"

services:
  raster-publisher:
    image: terrabrasilis/raster-publisher:v0.1
    volumes:       
      - /home/jether/Desktop/teste_deterb_imagem/servidor_imagens_projeto_fip_cerrado/scripts/to_process/translate:/usr/local/data/processed
      - /home/jether/Desktop/teste_deterb_imagem/servidor_imagens_projeto_fip_cerrado/scripts/:/usr/local/raster-publisher/log
      - /home/jether/Desktop/DEV/workspace/terrabrasilis/terrabrasilis-webapp/python-microservices/raster-publisher/src/config/:/usr/local/data/config